spring.application.name=demo

spring.datasource.url=jdbc:mariadb://10.4.73.115:3306/empresa?connectTimeout=10000&socketTimeout=60000
spring.datasource.username=appuser
spring.datasource.password=apppass
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver

spring.datasource.hikari.connection-timeout=60000
spring.datasource.hikari.maximum-pool-size=5
spring.datasource.hikari.minimum-idle=2

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=false

spring.jackson.serialization.indent_output=true

app.estudiante.nombre=Franckarlos Barbosa